apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.service.portNumber}} # assume these value changes